### PR TITLE
Fee Restructure and Bulk Payment Implementation

### LINKED ISSUE #149: update Fee calculation
- [ ] Add the fee amount to the payment transaction instead of subtracting it from the amount to be paid.
- [ ] Remove TOTAL_FEE and leave a parameter for Kyodo and another for Community

### LINKED ISSUE #184: Batch payment of multiple agreements
**Description:**  Pay several agreements at once. User choose chain after selecting all agreements he/she wants to pay. Metamask is called to approve all payments at once. 

**Acceptance Criteria:** Payment is successfully made after completing the flow 

**Requirements:** Backend and smart contracts interactions 

**Context:** User making the payments of agreements he/she chose

### LINKED ISSUE #185: Remove community fee and selection

### PR DESCRIPTION
**Pull request by nomadbitcoin**
1. Fees are now paid by the payer.
2. Removed Vault dependency.
3. Removed community fee logic and stripped out TOTAL_FEE.
4. Front-end updated to new fee calculation for approvals.
5. Enabled bulk payment processing.

Closes #184
Closes #149
Closes #185

### CODE REVIEW

**Comment by danicuki** [comment]
erro:
cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xf9aD3D930AB5df972558636A2B8749e772aC9297","to":"0x36D20ACa29B8901Eb4AE9Fcd82cD467a046fb71c","data":"0x0778c358000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000055001429cfa759e94d2067f417df0ee232e96e1a0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000de0b6b3a7640000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted"},"stack":"{\n \"code\": -32603,\n \"message\": \"Internal JSON-RPC error.\",\n \"data\": {\n \"code\": -32000,\n \"message\": \"execution reverted\"\n },\n \"stack\": \"Error: Internal JSON-RPC error.\\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44976)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45978\\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:53970\"\n}\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44976)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45978\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:53970"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)


Quando tento na Core

**Comment by danicuki** [comment]
Precisa de alguma maneira mostrar no front o cálculo do valor (valor pago + taxa) antes de abrir a metamask pra aprovar. Como está fica estranho pro usuário, que escolhe pagar um valor e na hora que abre a carteira aparece outro

**Comment by danicuki** [comment]
let's try to make one PRs per issue and treat them separately. One PR per feature please

**Comment by nomadbitcoin** [comment]
Contracts updated on Core Network, please try it again

**Review by danicuki — APPROVED** [review]

**Pull request merged**
